package com.abaferas.moneyeye.domain.utils

object Constants {
    const val TABLE_USER = "user"
    const val TABLE_ACCOUNT = "account"
    const val TABLE_RECORDS = "records"
    const val TABLE_CATEGORY = "category"
    const val TABLE_CATEGORIES = "categories"
    const val TYPE_PAYMENT = "payment"
    const val TYPE_INCOME = "income"
    const val REPEAT_ONE_TIME = "one_time"
    const val REPEAT_WEEKLY = "weekly"
    const val REPEAT_MONTHLY = "monthly"
    const val REPEAT_YEARLY = "yearly"
    const val REPEAT_THREE_MONTH = "per_three_month"
    const val REPEAT_FOUR_MONTH = "per_four_month"
    const val REPEAT_SIX_MONTH = "per_six_month"
    const val COLUMN_ID = "id"
    const val COLUMN_USER_ID = "userId"
    const val COLUMN_NAME = "name"
    const val COLUMN_SYNCED = "synced"
    const val COLUMN_BALANCE = "balance"
    const val COLUMN_INCOME = "income"
    const val COLUMN_ACCOUNT_ID = "accountId"
    const val COLUMN_CATEGORY_ID = "categoryId"
    const val COLUMN_AMOUNT = "amount"
    const val COLUMN_NOTE = "note"
    const val COLUMN_QUANTITY = "quantity"
    const val COLUMN_TOTAL = "total"
    const val COLUMN_TYPE = "type"
    const val COLUMN_REPEAT = "repeat"
    const val COLUMN_DATE = "date"
    const val COLUMN_DUE_DATE = "dueDate"
    const val COLUMN_FIRST_NAME = "firstName"
    const val COLUMN_LAST_NAME = "lastName"
    const val COLUMN_EMAIL = "email"
    const val COLUMN_PASSWORD = "password"
    const val COLUMN_TRANSACTION_ID = "transactionId"
    const val DATASTORE_NAME = "datastore_settings"
    const val LOGIN_KEY = "login"
    const val ANIMATION_DURATION = 300
    const val MESSAGE_INVALID_INPUT = "input isn't valid"
    const val MESSAGE_INVALID_EMAIL = "email isn't valid"
    const val MESSAGE_INVALID_PASSWORD = "password isn't valid"
    const val MESSAGE_INVALID_PASSWORD_CONFIRMATION = "password doesn't match"
    const val LABEL_FIRST_NAME = "First Name"
    const val LABEL_LAST_NAME = "Last Name"
    const val LABEL_EMAIL = "E-Mail"
    const val LABEL_PASSWORD = "Password"
    const val LABEL_PASSWORD_CONFIRM = "Password confirm"

}
